# Generated by Django 3.2.15 on 2022-09-18 09:42

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('department_short_description', models.TextField()),
                ('department_description', ckeditor.fields.RichTextField(default='Nothing')),
                ('department_image', models.ImageField(upload_to='Department/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-department_name',),
            },
        ),
        migrations.CreateModel(
            name='DonationCorporateBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='Corporate Company Logo')),
                ('company_name_address', models.CharField(max_length=255)),
                ('committed_amount', models.CharField(max_length=255)),
                ('donated_amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DonationCorporateOthers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='Corporate Company Logo')),
                ('company_name_address', models.CharField(max_length=255)),
                ('committed_amount', models.CharField(blank=True, default='0', max_length=255)),
                ('donated_amount', models.CharField(blank=True, default='0', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DonationGoverment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='default.png', upload_to='Donatiom/Goverment Donation')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DonationOver10kTo1Lac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_address', models.CharField(max_length=255)),
                ('committed_amount', models.CharField(max_length=255)),
                ('recieved_amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DonationOver10Lac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_address', models.CharField(max_length=255)),
                ('committed_amount', models.CharField(max_length=255)),
                ('recieved_amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DonationOver1LacTo5Lac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_address', models.CharField(max_length=255)),
                ('committed_amount', models.CharField(max_length=255)),
                ('recieved_amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DonationOver5LacsTo10Lac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_address', models.CharField(max_length=255)),
                ('committed_amount', models.CharField(max_length=255)),
                ('recieved_amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DonationOverseas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_address', models.CharField(max_length=255)),
                ('committed_amount', models.CharField(max_length=255)),
                ('donated_amount', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoverningBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(default='default.png', upload_to='Governing Body')),
            ],
        ),
        migrations.CreateModel(
            name='ManagementTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('profile_pic', models.ImageField(default='default.png', upload_to='Management Team')),
            ],
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='default.png', upload_to='Service/logo')),
                ('service_name', models.CharField(max_length=255)),
                ('service_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('service_image', models.FileField(upload_to='Service/Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('excert', models.TextField()),
                ('news_description', ckeditor.fields.RichTextField(default='Nothing')),
                ('news_thumbnail', models.ImageField(upload_to='News/News Thumbnail/')),
                ('news_image', models.ImageField(upload_to='News/News Image/')),
                ('news_views', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('news_category', models.ManyToManyField(to='main_application_amcgh.NewsCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('gallery_image', models.ImageField(default='default.png', upload_to='Gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_application_amcgh.gallerycategory')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('designation', models.TextField()),
                ('degree', models.CharField(max_length=255)),
                ('profile_pic', models.FileField(upload_to='Doctor_Profile_Pic')),
                ('research_publication', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('appointment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ManyToManyField(to='main_application_amcgh.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Department_Slug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_application_amcgh.department')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
