# Generated by Django 3.2.15 on 2022-09-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application_amcgh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, default='None', max_length=255)),
                ('donor_logo', models.ImageField(default='default.png', upload_to='Donors')),
            ],
        ),
    ]
