# Generated by Django 3.2.15 on 2022-12-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_application_amcgh', '0003_governingbody_institution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('-sorting_order',)},
        ),
        migrations.AddField(
            model_name='doctor',
            name='sorting_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
